# Generated by Django 6.0.5 on 2026-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='farmer_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
