# Generated by Django 6.0.5 on 2026-06-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('energy', 'Energy Feeds'), ('protein', 'Protein Feeds'), ('roughage', 'Roughage'), ('supplements', 'Supplements'), ('minerals', 'Minerals')], default='general', max_length=20),
        ),
    ]
