# Generated by Django 6.0.5 on 2026-06-28 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0004_alter_payment_amount_alter_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(choices=[('concentrates', 'Concentrates'), ('roughages', 'Roughages'), ('minerals', 'Minerals & Supplements')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feed',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('bale', 'Bale'), ('sack', 'Sack'), ('liter', 'Liter (L)'), ('bundle', 'Bundle'), ('bag', 'Bag')], default='kg', max_length=20),
        ),
    ]
