# Generated by Django 6.0.5 on 2026-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0005_feed_date_added_alter_feed_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='added_at',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feed',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'feed')},
        ),
    ]
