# Generated by Django 5.2.14 on 2026-07-25 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0006_rename_added_at_cartitem_date_added_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heat_date', models.DateField(blank=True, null=True)),
                ('insemination_date', models.DateField()),
                ('insemination_type', models.CharField(choices=[('AI', 'Artificial Insemination'), ('Natural', 'Natural Service')], default='AI', max_length=20)),
                ('bull_or_sire', models.CharField(blank=True, help_text='Bull ID or AI sire name', max_length=100, null=True)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('actual_calving_date', models.DateField(blank=True, null=True)),
                ('calf_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('calf_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('Inseminated', 'Inseminated'), ('Pregnant', 'Confirmed Pregnant'), ('Calved', 'Calved'), ('Failed', 'Failed / Repeat')], default='Inseminated', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False, help_text='True after 2-week calving alert has been sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='farmer_app.cow')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-insemination_date'],
            },
        ),
    ]
