# Generated by Django 6.0.5 on 2026-07-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0007_breedingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedorder',
            name='payment_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
