# Generated by Django 6.0.5 on 2026-07-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0008_feedorder_payment_method_feedorder_payment_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_price_per_liter', models.DecimalField(decimal_places=2, default=80.0, help_text='Amount paid to farmer per liter (KES)', max_digits=10)),
                ('collector_commission_per_liter', models.DecimalField(decimal_places=2, default=3.0, help_text='Commission paid to collector per liter (KES)', max_digits=10)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
    ]
