# Generated by Django 6.0.5 on 2026-07-26 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0009_milkrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='cow',
            field=models.ForeignKey(blank=True, help_text='Optionally link to a specific cow for per-cow analytics', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_records', to='farmer_app.cow'),
        ),
        migrations.CreateModel(
            name='CollectorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 — Poor'), (2, '2 — Fair'), (3, '3 — Average'), (4, '4 — Good'), (5, '5 — Excellent')])),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('milk_record', models.OneToOneField(blank=True, help_text='The collection visit this rating is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='farmer_app.milkrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('farmer', 'milk_record')},
            },
        ),
    ]
