# Generated by Django 6.0.5 on 2026-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0010_add_cow_to_milkrecord_and_collector_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('milk_sale', 'Milk Sale'), ('feed_order', 'Feed Order'), ('milk_deduction', 'Milk Deduction'), ('commission', 'Collector Commission')], max_length=20),
        ),
    ]
